/**
 * Countries with dial codes for contact forms.
 * Format: { value: country name (stored), label: display name, dialCode: e.g. "+971" }
 * Sorted by country name.
 */
export interface CountryOption {
  value: string
  label: string
  dialCode: string
}

export const countriesWithDialCodes: CountryOption[] = [
  { value: "Afghanistan", label: "Afghanistan", dialCode: "+93" },
  { value: "Albania", label: "Albania", dialCode: "+355" },
  { value: "Algeria", label: "Algeria", dialCode: "+213" },
  { value: "Andorra", label: "Andorra", dialCode: "+376" },
  { value: "Angola", label: "Angola", dialCode: "+244" },
  { value: "Argentina", label: "Argentina", dialCode: "+54" },
  { value: "Armenia", label: "Armenia", dialCode: "+374" },
  { value: "Australia", label: "Australia", dialCode: "+61" },
  { value: "Austria", label: "Austria", dialCode: "+43" },
  { value: "Azerbaijan", label: "Azerbaijan", dialCode: "+994" },
  { value: "Bahrain", label: "Bahrain", dialCode: "+973" },
  { value: "Bangladesh", label: "Bangladesh", dialCode: "+880" },
  { value: "Belarus", label: "Belarus", dialCode: "+375" },
  { value: "Belgium", label: "Belgium", dialCode: "+32" },
  { value: "Belize", label: "Belize", dialCode: "+501" },
  { value: "Benin", label: "Benin", dialCode: "+229" },
  { value: "Bhutan", label: "Bhutan", dialCode: "+975" },
  { value: "Bolivia", label: "Bolivia", dialCode: "+591" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", dialCode: "+387" },
  { value: "Botswana", label: "Botswana", dialCode: "+267" },
  { value: "Brazil", label: "Brazil", dialCode: "+55" },
  { value: "Brunei", label: "Brunei", dialCode: "+673" },
  { value: "Bulgaria", label: "Bulgaria", dialCode: "+359" },
  { value: "Burkina Faso", label: "Burkina Faso", dialCode: "+226" },
  { value: "Cambodia", label: "Cambodia", dialCode: "+855" },
  { value: "Cameroon", label: "Cameroon", dialCode: "+237" },
  { value: "Canada", label: "Canada", dialCode: "+1" },
  { value: "Chile", label: "Chile", dialCode: "+56" },
  { value: "China", label: "China", dialCode: "+86" },
  { value: "Colombia", label: "Colombia", dialCode: "+57" },
  { value: "Costa Rica", label: "Costa Rica", dialCode: "+506" },
  { value: "Croatia", label: "Croatia", dialCode: "+385" },
  { value: "Cuba", label: "Cuba", dialCode: "+53" },
  { value: "Cyprus", label: "Cyprus", dialCode: "+357" },
  { value: "Czech Republic", label: "Czech Republic", dialCode: "+420" },
  { value: "Denmark", label: "Denmark", dialCode: "+45" },
  { value: "Dominican Republic", label: "Dominican Republic", dialCode: "+1" },
  { value: "Ecuador", label: "Ecuador", dialCode: "+593" },
  { value: "Egypt", label: "Egypt", dialCode: "+20" },
  { value: "El Salvador", label: "El Salvador", dialCode: "+503" },
  { value: "Estonia", label: "Estonia", dialCode: "+372" },
  { value: "Ethiopia", label: "Ethiopia", dialCode: "+251" },
  { value: "Finland", label: "Finland", dialCode: "+358" },
  { value: "France", label: "France", dialCode: "+33" },
  { value: "Gabon", label: "Gabon", dialCode: "+241" },
  { value: "Georgia", label: "Georgia", dialCode: "+995" },
  { value: "Germany", label: "Germany", dialCode: "+49" },
  { value: "Ghana", label: "Ghana", dialCode: "+233" },
  { value: "Greece", label: "Greece", dialCode: "+30" },
  { value: "Guatemala", label: "Guatemala", dialCode: "+502" },
  { value: "Hong Kong", label: "Hong Kong", dialCode: "+852" },
  { value: "Hungary", label: "Hungary", dialCode: "+36" },
  { value: "Iceland", label: "Iceland", dialCode: "+354" },
  { value: "India", label: "India", dialCode: "+91" },
  { value: "Indonesia", label: "Indonesia", dialCode: "+62" },
  { value: "Iran", label: "Iran", dialCode: "+98" },
  { value: "Iraq", label: "Iraq", dialCode: "+964" },
  { value: "Ireland", label: "Ireland", dialCode: "+353" },
  { value: "Israel", label: "Israel", dialCode: "+972" },
  { value: "Italy", label: "Italy", dialCode: "+39" },
  { value: "Jamaica", label: "Jamaica", dialCode: "+1" },
  { value: "Japan", label: "Japan", dialCode: "+81" },
  { value: "Jordan", label: "Jordan", dialCode: "+962" },
  { value: "Kazakhstan", label: "Kazakhstan", dialCode: "+7" },
  { value: "Kenya", label: "Kenya", dialCode: "+254" },
  { value: "Kuwait", label: "Kuwait", dialCode: "+965" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", dialCode: "+996" },
  { value: "Latvia", label: "Latvia", dialCode: "+371" },
  { value: "Lebanon", label: "Lebanon", dialCode: "+961" },
  { value: "Libya", label: "Libya", dialCode: "+218" },
  { value: "Lithuania", label: "Lithuania", dialCode: "+370" },
  { value: "Luxembourg", label: "Luxembourg", dialCode: "+352" },
  { value: "Macau", label: "Macau", dialCode: "+853" },
  { value: "Malaysia", label: "Malaysia", dialCode: "+60" },
  { value: "Maldives", label: "Maldives", dialCode: "+960" },
  { value: "Malta", label: "Malta", dialCode: "+356" },
  { value: "Mauritius", label: "Mauritius", dialCode: "+230" },
  { value: "Mexico", label: "Mexico", dialCode: "+52" },
  { value: "Moldova", label: "Moldova", dialCode: "+373" },
  { value: "Monaco", label: "Monaco", dialCode: "+377" },
  { value: "Mongolia", label: "Mongolia", dialCode: "+976" },
  { value: "Montenegro", label: "Montenegro", dialCode: "+382" },
  { value: "Morocco", label: "Morocco", dialCode: "+212" },
  { value: "Mozambique", label: "Mozambique", dialCode: "+258" },
  { value: "Myanmar", label: "Myanmar", dialCode: "+95" },
  { value: "Nepal", label: "Nepal", dialCode: "+977" },
  { value: "Netherlands", label: "Netherlands", dialCode: "+31" },
  { value: "New Zealand", label: "New Zealand", dialCode: "+64" },
  { value: "Nigeria", label: "Nigeria", dialCode: "+234" },
  { value: "North Macedonia", label: "North Macedonia", dialCode: "+389" },
  { value: "Norway", label: "Norway", dialCode: "+47" },
  { value: "Oman", label: "Oman", dialCode: "+968" },
  { value: "Pakistan", label: "Pakistan", dialCode: "+92" },
  { value: "Palestine", label: "Palestine", dialCode: "+970" },
  { value: "Panama", label: "Panama", dialCode: "+507" },
  { value: "Paraguay", label: "Paraguay", dialCode: "+595" },
  { value: "Peru", label: "Peru", dialCode: "+51" },
  { value: "Philippines", label: "Philippines", dialCode: "+63" },
  { value: "Poland", label: "Poland", dialCode: "+48" },
  { value: "Portugal", label: "Portugal", dialCode: "+351" },
  { value: "Qatar", label: "Qatar", dialCode: "+974" },
  { value: "Romania", label: "Romania", dialCode: "+40" },
  { value: "Russia", label: "Russia", dialCode: "+7" },
  { value: "Rwanda", label: "Rwanda", dialCode: "+250" },
  { value: "Saudi Arabia", label: "Saudi Arabia", dialCode: "+966" },
  { value: "Senegal", label: "Senegal", dialCode: "+221" },
  { value: "Serbia", label: "Serbia", dialCode: "+381" },
  { value: "Singapore", label: "Singapore", dialCode: "+65" },
  { value: "Slovakia", label: "Slovakia", dialCode: "+421" },
  { value: "Slovenia", label: "Slovenia", dialCode: "+386" },
  { value: "South Africa", label: "South Africa", dialCode: "+27" },
  { value: "South Korea", label: "South Korea", dialCode: "+82" },
  { value: "Spain", label: "Spain", dialCode: "+34" },
  { value: "Sri Lanka", label: "Sri Lanka", dialCode: "+94" },
  { value: "Sudan", label: "Sudan", dialCode: "+249" },
  { value: "Sweden", label: "Sweden", dialCode: "+46" },
  { value: "Switzerland", label: "Switzerland", dialCode: "+41" },
  { value: "Syria", label: "Syria", dialCode: "+963" },
  { value: "Taiwan", label: "Taiwan", dialCode: "+886" },
  { value: "Tanzania", label: "Tanzania", dialCode: "+255" },
  { value: "Thailand", label: "Thailand", dialCode: "+66" },
  { value: "Tunisia", label: "Tunisia", dialCode: "+216" },
  { value: "Turkey", label: "Turkey", dialCode: "+90" },
  { value: "Uganda", label: "Uganda", dialCode: "+256" },
  { value: "Ukraine", label: "Ukraine", dialCode: "+380" },
  { value: "United Arab Emirates", label: "United Arab Emirates", dialCode: "+971" },
  { value: "United Kingdom", label: "United Kingdom", dialCode: "+44" },
  { value: "United States", label: "United States", dialCode: "+1" },
  { value: "Uruguay", label: "Uruguay", dialCode: "+598" },
  { value: "Uzbekistan", label: "Uzbekistan", dialCode: "+998" },
  { value: "Venezuela", label: "Venezuela", dialCode: "+58" },
  { value: "Vietnam", label: "Vietnam", dialCode: "+84" },
  { value: "Yemen", label: "Yemen", dialCode: "+967" },
  { value: "Zambia", label: "Zambia", dialCode: "+260" },
  { value: "Zimbabwe", label: "Zimbabwe", dialCode: "+263" },
  { value: "Other", label: "Other", dialCode: "" },
]

export function getDialCodeForCountry(countryValue: string): string {
  const found = countriesWithDialCodes.find(
    (c) => c.value.toLowerCase() === countryValue.toLowerCase()
  )
  return found?.dialCode ?? ""
}
